version: '3.7'

services:
  db:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'

  redis:
    image: redis:3.2.6-alpine

  private:
    privileged: true
    ports:
      - '9090:80'
    build:
      context: .
      dockerfile: Dockerfile
      target: stable
    links:
      - db
      - redis
    environment:
      HOST_NAME: '*'
      DB_HOST: db
      DB_USER: postgres
      DB_NAME: postgres
      DB_PASSWORD: ''
      DB_PUBLIC_USER: 'omaha_public'
      DB_PUBLIC_PASSWORD: 'omaha_public_password'
      REDIS_HOST: redis
      DJANGO_SETTINGS_MODULE: 'omaha_server.settings_local'
      OMAHA_SERVER_PRIVATE: 'True'
      AWS_STORAGE_BUCKET_NAME: 'aws_storage_bucket_name'
      AWS_ROLE: 'omaha-private'
    sysctls:
      net.core.somaxconn: 1024

  public:
    privileged: true
    ports:
      - '80:80'
    build:
      context: .
      dockerfile: Dockerfile
      target: stable
    links:
      - db
      - redis
      - private
    environment:
      HOST_NAME: '*'
      DB_HOST: db
      DB_USER: postgres
      DB_NAME: postgres
      DB_PASSWORD: ''
      DB_PUBLIC_USER: 'omaha_public'
      DB_PUBLIC_PASSWORD: 'omaha_public_password'
      REDIS_HOST: redis
      DJANGO_SETTINGS_MODULE: 'omaha_server.settings_local'
      OMAHA_SERVER_PRIVATE: 'False'
      AWS_STORAGE_BUCKET_NAME: 'aws_storage_bucket_name'
      AWS_ROLE: 'omaha-public'
    sysctls:
      net.core.somaxconn: 1024
